name: Release

on:
  push:
    tags:
      - 'Release/v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set release name
        run: echo ::set-env name=RELEASE_NAME::$(echo ${GITHUB_REF:11})

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

  publish:
    name: Publish Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Set release name
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:20})
      - name: Publish library
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: ./gradlew publish
